server:
  port: 8080
  address: localhost
# DataSource Config
spring:
  http:
    encoding.charset: UTF-8
    encoding.enable: true
    encoding.force: true
  #  datasource:
  #    driver-class-name: oracle.jdbc.OracleDriver
  #    type: com.zaxxer.hikari.HikariDataSource
  #    url: jdbc:oracle:thin:@112.35.32.77:1532:jd3
  #    username: s4i_purchase_project
  #    password: 'S4#scm.s01'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema: classpath:db/schema-mysql.sql
    data: classpath:db/data-mysql.sql
    url: jdbc:mysql:///moses?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: 123456
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  #开发配置为false,避免修改模板还要重启服务器
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
  mail:
    #邮件协议smtp
    host: smtp.qq.com
    #发送者的邮件的用户名
    username: 287664409@qq.com
    #使用的编码
    default-encoding: utf-8
    #移动端客户授权码(在邮箱中设置)
    password: digwjstljssobgjj
mybatis-plus:
  mapper-locations: classpath*:mapper/*/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples.quickstart: debug
